#pragma once

/// @file zonal_harmonics.h
/// A precomputed set of zonal harmonic coefficients Jₙ for a named gravity
/// standard — the home for the Jₖ in the common astrophysics library.
///
/// The Jₙ are STATIC (no altitude/latitude/longitude dependence), so they are
/// generated exactly ONCE, here at construction, to the caller's tolerance, and
/// then stored and looked up cheaply thereafter (compute-once; the generators do
/// not re-run per propagation step). For each degree n:
///
///   - even zonals (J₂, J₄, J₆ …) are DERIVED from the level ellipsoid
///     (EquipotentialEllipsoid::J2n), itself generative in the four defining
///     parameters;
///   - odd zonals (J₃, J₅ …) break equatorial symmetry and are EMPIRICAL. They
///     are generated from the standard's born-digital normalized coefficient via
///       Jₙ = −√(2n+1) · C̄ₙ₀,
///     computed once through the tracked (arbitrary-precision-capable) sqrt — so
///     the precision scales with T and no truncated Jₙ is stored (this resolves
///     the R04 provenance concern by computing from the published C̄ₙ₀, not a
///     copied-down Jₙ).
///
/// Each stored Jₙ carries its three-error budget; the table records the standard
/// it realizes. Adding a degree is adding a coefficient; swapping standards is
/// selecting a different factory.
///
/// @par Sources (born-digital)
/// - EGM2008 / IERS Conventions 2010, Table 6.2 — normalized C̄ₙ₀ (iau-a3 NSFA).
/// - Spacetrack Report No. 3 (Hoots & Roehrich 1980) — WGS72 J₃.

#include "../geodesy/equipotential_ellipsoid.h"
#include "../math/tracked_value.h"

#include <string>
#include <utility>
#include <vector>

namespace constants {

/// Precomputed, standard-tagged table of zonal harmonics Jₙ.
///
/// @tparam T  Underlying numeric type.
template<typename T>
class ZonalHarmonics {
public:
    /// Build the table for `standard` on `earth`, up to degree `max_degree`.
    /// Even zonals come from the ellipsoid; odd zonals are taken from `odd_jn`
    /// (already generated by the standard factory). All entries are stored as
    /// precomputed TrackedValues — this constructor is the one-time init.
    ZonalHarmonics(const geodesy::EquipotentialEllipsoid<T>& earth,
                   std::string standard,
                   const std::vector<std::pair<int, math::TrackedValue<T>>>& odd_jn,
                   int max_degree)
        : standard_(std::move(standard)),
          jn_(static_cast<std::size_t>(max_degree) + 1, math::exact<T>(0)) {
        for (int n = 2; n <= max_degree; ++n) {
            if (n % 2 == 0) {
                jn_[static_cast<std::size_t>(n)] = earth.J2n(n / 2);
            } else {
                jn_[static_cast<std::size_t>(n)] = lookup(odd_jn, n);
            }
        }
    }

    /// Precomputed Jₙ (n ≥ 2). Returns exact zero outside the stored range.
    math::TrackedValue<T> Jn(int n) const {
        if (n >= 2 && n < static_cast<int>(jn_.size())) {
            return jn_[static_cast<std::size_t>(n)];
        }
        return math::exact<T>(0);
    }

    /// The standard this table realizes (e.g. "EGM2008/IERS2010").
    const std::string& standard() const { return standard_; }

    /// Highest degree stored.
    int max_degree() const { return static_cast<int>(jn_.size()) - 1; }

    // --- Standard factories (born-digital coefficients sourced within) -------

    /// EGM2008 / IERS 2010 odd zonals from the normalized C̄ₙ₀, generated as
    /// Jₙ = −√(2n+1)·C̄ₙ₀. C̄ₙ₀ are VERBATIM from the in-repo born-digital NGA
    /// EGM2008 coefficient file (datalib/EGM-08norm100.txt, 15 significant
    /// digits; transcribed by tools/gen_egm_zonals.py — R04 closed: the prior
    /// 7-digit values were transcription artifacts at the 5th figure for
    /// n = 5, 7, 9). Even zonals come from the IERS 2010 reference ellipsoid.
    static ZonalHarmonics egm2008(const T& series_tolerance) {
        using TV = math::TrackedValue<T>;
        geodesy::EquipotentialEllipsoid<T> earth =
            geodesy::EquipotentialEllipsoid<T>::iers2010(series_tolerance);
        std::vector<std::pair<int, TV>> odd;
        odd.push_back({3, jn_from_cbar(3, "0.957161207093473e-6")});
        odd.push_back({5, jn_from_cbar(5, "0.0686702913736681e-6")});
        odd.push_back({7, jn_from_cbar(7, "0.0905120844521618e-6")});
        odd.push_back({9, jn_from_cbar(9, "0.0280180753216300e-6")});
        return ZonalHarmonics(earth, "EGM2008/IERS2010", odd, 9);
    }

    /// WGS72 / Spacetrack Report #3: J₃ is given directly (COMMON/C1 block).
    static ZonalHarmonics wgs72(const T& series_tolerance) {
        using TV = math::TrackedValue<T>;
        geodesy::EquipotentialEllipsoid<T> earth =
            geodesy::EquipotentialEllipsoid<T>::wgs72(series_tolerance);
        std::vector<std::pair<int, TV>> odd;
        // J₃ is a gravity-MODEL coefficient (no published formal σ): its finite
        // written digits are a model-fidelity limit (accuracy), while its binary
        // storage is a computational precision that scales with T. Encoded with
        // model_coefficient per the 2026-06-05 panel ruling (uniform, by-nature
        // categorization — not the prior path-based hybrid).
        odd.push_back({3, TV::model_coefficient("-0.253881e-5")});
        return ZonalHarmonics(earth, "WGS72/SR3", odd, 4);
    }

private:
    /// Generate an odd zonal from its normalized coefficient: Jₙ = −√(2n+1)·C̄ₙ₀.
    /// √(2n+1) is the tracked, arbitrary-precision sqrt. C̄ₙ₀ (the full
    /// 15-significant-digit in-repo EGM2008 file value) is encoded with
    /// `measured` carrying the PUBLISHED formal-error grade (IERS Conventions
    /// 2010 Table 6.2: ±0.49e-11-class on the low-degree C̄ₙ₀) — the by-nature
    /// channel for a field coefficient with a genuine σ (the R5/O2 re-encode;
    /// the prior model_coefficient digit-floor convention was honest at 7
    /// written digits but would UNDER-claim at the file's 15). Binary storage
    /// remains a T-scaling precision; σ is not a decimal ULP (CR1-b clean).
    static math::TrackedValue<T> jn_from_cbar(int n, const char* cbar_n0) {
        return -sqrt(math::exact<T>(2 * n + 1))
             * math::TrackedValue<T>::measured(cbar_n0, "0.49e-11");
    }

    static math::TrackedValue<T> lookup(
        const std::vector<std::pair<int, math::TrackedValue<T>>>& v, int n) {
        for (const std::pair<int, math::TrackedValue<T>>& e : v) {
            if (e.first == n) return e.second;
        }
        return math::exact<T>(0);
    }

    std::string standard_;
    std::vector<math::TrackedValue<T>> jn_;  ///< jn_[n] = precomputed Jₙ.
};

}  // namespace constants
