%% audit_eq9_signs.m
%% Numerical verification of Eq. (9) signs.
%%
%% The type-2 generating function F2(old coords, new momenta) = W(l, L'')
%% pairs the observable configuration (osculating angles l_j) with the
%% conserved quantities (mean actions L_j''). This is the Hamilton-Jacobi
%% structure: configuration paired with constants of motion.
%%
%% The type-2 relations give:
%%   L_j  = dW/dl_j   = L_j'' + dS/dl_j     => L_j - L_j'' = +dS/dl_j
%%   l_j'' = dW/dL_j'' = l_j   + dS/dL_j''   => l_j - l_j'' = -dS/dL_j''
%%
%% These match BH61 Eq. (9) exactly (with l_j -> l_j'' replacement at first order).
%%
%% This script verifies numerically with a concrete 1-DOF example.
%%
%% It also tests the INVERSE generating function W(l'', L) to confirm
%% that it gives opposite signs (because it answers the reverse question:
%% given mean angles, find osculating actions).

printf('============================================================\n');
printf('SIGN AUDIT: Eq. (9) generating function convention\n');
printf('============================================================\n\n');

%% Set up a simple 1-DOF canonical system
%% Variables: (x, y) = (L, l), one degree of freedom
%% F = x^2/2 (a harmonic oscillator Hamiltonian in BH61's F=-H convention)
%%
%% Near-identity canonical transformation generated by:
%% W(y', x) = x*y' + eps*S(x, y')
%%
%% Choose S(x, y') = x * sin(y') (a simple function)

eps_param = 0.01;  % small parameter

%% The type-2 generating function:
%% W(y', x) = x*y' + eps*x*sin(y')
%%
%% Type-2 relations:
%%   y = dW/dx = y' + eps*sin(y')
%%   x' = dW/dy' = x + eps*x*cos(y')

%% Forward map: given (x, y), find (x', y')
%% From y = y' + eps*sin(y'): solve for y' given y (iteratively)
%% From x' = x + eps*x*cos(y') = x*(1 + eps*cos(y'))

function [xp, yp] = forward_transform(x, y, eps_p)
  % Solve y = yp + eps*sin(yp) for yp
  yp = y;
  for iter = 1:50
    yp = yp + (y - yp - eps_p*sin(yp)) / (1 + eps_p*cos(yp));
  end
  xp = x * (1 + eps_p*cos(yp));
end

function [x, y] = inverse_transform(xp, yp, eps_p)
  % Given (x', y'), find (x, y)
  % From x' = x*(1 + eps*cos(y')): x = x'/(1 + eps*cos(y'))
  x = xp / (1 + eps_p*cos(yp));
  % From y = y' + eps*sin(y'):
  y = yp + eps_p*sin(yp);
end

%% TEST 1: Verify the transformation is canonical
%% Compute the Poisson bracket {y', x'} in the (x, y) variables
%% Should equal +1 (modern convention) or -1 (BH61 convention)

printf('--- TEST 1: Verify transformation is canonical ---\n');
eps_fd = 1e-8;
x0 = 1.5; y0 = 1.0;
[xp0, yp0] = forward_transform(x0, y0, eps_param);

% dy'/dx
[xp_px, yp_px] = forward_transform(x0+eps_fd, y0, eps_param);
[xp_mx, yp_mx] = forward_transform(x0-eps_fd, y0, eps_param);
dyp_dx = (yp_px - yp_mx)/(2*eps_fd);
dxp_dx = (xp_px - xp_mx)/(2*eps_fd);

% dy'/dy
[xp_py, yp_py] = forward_transform(x0, y0+eps_fd, eps_param);
[xp_my, yp_my] = forward_transform(x0, y0-eps_fd, eps_param);
dyp_dy = (yp_py - yp_my)/(2*eps_fd);
dxp_dy = (xp_py - xp_my)/(2*eps_fd);

% {y', x'}_modern = dy'/dx * dx'/dy - dy'/dy * dx'/dx
pb_modern = dyp_dx * dxp_dy - dyp_dy * dxp_dx;
printf('  {y'', x''}_modern = %.10f (should be +1 or -1)\n', pb_modern);

% {x', y'}_modern = dx'/dx * dy'/dy - dx'/dy * dy'/dx
pb_modern2 = dxp_dx * dyp_dy - dxp_dy * dyp_dx;
printf('  {x'', y''}_modern = %.10f (should be +1 or -1)\n', pb_modern2);

printf('\n');

%% TEST 2: Check the generating function relations
%% y - y' = ??? * dS/dx  (evaluated at which point?)
%% x - x' = ??? * dS/dy'

printf('--- TEST 2: Generating function relation signs ---\n');

% Compute y - y' and x - x'
[xp0, yp0] = forward_transform(x0, y0, eps_param);
dy_diff = y0 - yp0;  % y - y'
dx_diff = x0 - xp0;  % x - x'

% S(x, y') = x * sin(y')
% dS/dx = sin(y'), evaluated at (x0, yp0)
dS_dx = sin(yp0);
% dS/dy' = x * cos(y'), evaluated at (x0, yp0)
dS_dyp = x0 * cos(yp0);

printf('  y - y''  = %.10f\n', dy_diff);
printf('  eps*dS/dx = %.10f\n', eps_param * dS_dx);
printf('  Ratio (y-y'')/(eps*dS/dx) = %.10f (should be +1 or -1)\n', dy_diff/(eps_param*dS_dx));
printf('\n');
printf('  x - x''  = %.10f\n', dx_diff);
printf('  eps*dS/dy'' = %.10f\n', eps_param * dS_dyp);
printf('  Ratio (x-x'')/(eps*dS/dy'') = %.10f (should be +1 or -1)\n', dx_diff/(eps_param*dS_dyp));

printf('\n');

%% TEST 3: Map to BH61 notation
%% BH61: x = L (momentum), y = l (coordinate)
%% x' = L'', y' = l''
%%
%% From TEST 2:
%%   l - l'' = y - y' = +eps * dS/dx = +eps * dS/dL
%%   L - L'' = x - x' = ??? * eps * dS/dl''
%%
%% BH61 Eq. (9) claims:
%%   l - l'' = -dS/dL''
%%   L - L'' = +dS/dl''
%%
%% Let's see what the actual signs are.

printf('--- TEST 3: Map to BH61 Eq. (9) notation ---\n');
printf('  x = L (momentum), y = l (coordinate)\n');
printf('  x'' = L'''', y'' = l''''\n\n');

ratio_l = dy_diff / (eps_param * dS_dx);
ratio_L = dx_diff / (eps_param * dS_dyp);

printf('  l - l'''' = %+.1f * eps * dS/dL   (at L, l'''')\n', ratio_l);
printf('  L - L'''' = %+.1f * eps * dS/dl''''  (at L, l'''')\n', ratio_L);

printf('\n  BH61 Eq. (9) claims:\n');
printf('  l - l'''' = -dS/dL''''\n');
printf('  L - L'''' = +dS/dl''''\n');

if abs(ratio_l - 1) < 0.01 && abs(ratio_L + 1) < 0.01
  printf('\n  Our type-2 gives: l-l'''' = +dS/dL, L-L'''' = -dS/dl''''\n');
  printf('  BH61 Eq. (9) has: l-l'''' = -dS/dL'''', L-L'''' = +dS/dl''''\n');
  printf('  OPPOSITE SIGNS on both equations.\n');
  printf('  This means BH61 defines S with the OPPOSITE sign from the type-2 convention.\n');
  printf('  Equivalently: BH61''s (S1+S1*) = -eps*S in our type-2 convention.\n');
elseif abs(ratio_l + 1) < 0.01 && abs(ratio_L - 1) < 0.01
  printf('\n  MATCH: signs agree with BH61 Eq. (9).\n');
else
  printf('\n  UNEXPECTED ratios. Something is wrong.\n');
end

printf('\n');

%% TEST 4: Verify using the INVERSE type-2 generating function
%% Perhaps BH61 uses W(l, L'') = sum L''*l + S(L'', l)
%% i.e., old coordinates and new momenta (instead of new coords and old momenta)

printf('--- TEST 4: Try inverse type-2: W(l, L'''') = L''''*l + eps*S(L'''', l) ---\n');

% W(l, L'') = L''*l + eps*L''*sin(l)
% Relations:
%   L = dW/dl = L'' + eps*L''*cos(l) = L''*(1 + eps*cos(l))
%   l'' = dW/dL'' = l + eps*sin(l)
%
% So: l'' - l = +eps*sin(l) = +eps*dS/dL''(l, L'')  where S = L''*sin(l)
%     L - L'' = +eps*L''*cos(l) = ... hmm

% Actually let me use S(L'', l) = L''*sin(l)
% dS/dL'' = sin(l)
% dS/dl = L''*cos(l)
% Then: l'' = l + eps*dS/dL'' = l + eps*sin(l)
%        L = L''*(1 + eps*cos(l)) = L'' + eps*L''*cos(l)
%
% Rearranging:
%   l - l'' = -eps*sin(l) = -eps*dS/dL''  ← matches BH61 Eq. (9) first line!
%   L - L'' = +eps*L''*cos(l) = +eps*dS/dl  ← need to check dS/dl

% dS/dl = L''*cos(l), and the correction L - L'' = eps*L''*cos(l) = +eps*dS/dl
% But BH61 Eq. (9) says L - L'' = +dS/dl'' (derivative w.r.t. l'')

% At first order in eps: l ≈ l'' (since l'' = l + eps*...), so dS/dl ≈ dS/dl''.
% Therefore L - L'' = +eps*dS/dl'' to first order. This matches BH61!

% Let me verify numerically
L_pp = 1.5;  % new momentum (L'')
l_old = 1.0;  % old coordinate (l)

% From W(l, L'') = L''*l + eps*L''*sin(l):
l_pp_val = l_old + eps_param*sin(l_old);  % l'' = dW/dL'' = l + eps*sin(l)
L_old = L_pp*(1 + eps_param*cos(l_old));  % L = dW/dl = L'' + eps*L''*cos(l)

l_diff = l_old - l_pp_val;  % l - l''
L_diff = L_old - L_pp;      % L - L''

% S(L'', l) = L''*sin(l)
% dS/dL'' = sin(l) ≈ sin(l'') to first order
dS_dLpp = sin(l_old);       % evaluated at old l
dS_dLpp_new = sin(l_pp_val); % evaluated at new l''

% dS/dl = L''*cos(l) ≈ dS/dl'' to first order
dS_dl = L_pp*cos(l_old);
dS_dlpp = L_pp*cos(l_pp_val);

printf('  l - l'''' = %.10f\n', l_diff);
printf('  -eps*dS/dL'''' = %.10f  (BH61 Eq. 9 first line)\n', -eps_param*dS_dLpp_new);
printf('  Difference: %.2e\n', abs(l_diff - (-eps_param*dS_dLpp_new)));
printf('\n');
printf('  L - L'''' = %.10f\n', L_diff);
printf('  +eps*dS/dl'''' = %.10f  (BH61 Eq. 9 second line)\n', +eps_param*dS_dlpp);
printf('  Difference: %.2e\n', abs(L_diff - (+eps_param*dS_dlpp)));

printf('\n');
if abs(l_diff - (-eps_param*dS_dLpp_new)) < 1e-4 && abs(L_diff - (+eps_param*dS_dlpp)) < 1e-4
  printf('PASS: BH61 Eq. (9) signs are correct for type-2 W(l, L'''') convention.\n');
  printf('\n');
  printf('CONCLUSION:\n');
  printf('The type-2 generating function is F2(old coords, new momenta) by definition.\n');
  printf('For the forward Brouwer transformation (L,l) -> (L'''',l''''):\n');
  printf('  old coords = l, new momenta = L''''.\n');
  printf('  W(l, L'''') = L''''*l + eps*S(L'''', l)\n');
  printf('The relations are:\n');
  printf('  l'''' = dW/dL''''  =>  l'''' - l = +eps*dS/dL''''  =>  l - l'''' = -dS/dL''''\n');
  printf('  L  = dW/dl    =>  L - L'''' = +eps*dS/dl = +eps*dS/dl'''' (first order)\n');
  printf('\nThis matches BH61 Eq. (9) exactly.\n');
else
  printf('FAIL: signs do not match.\n');
end

printf('\n============================================================\n');
