% Auto-generated by derive_dS1_dLGH.m
% Per-harmonic dS1 partial derivatives.
% To use, run this after declaring the same symbols.

dP0_dL = k2*mu**2*(G**2 - 3*H**2)*(-e**2*sin(f)**2 + 3*e*cos(f) + 3)*sin(f)/(2*G**3*L**3*e*(e**2 - 1));
dQ1_dL = -3*k2*mu**2*(G**2 - H**2)*(e*cos(f) + 2)*sin(f)*cos(2*f + 2*g)/(2*G**3*L**3*e*(e**2 - 1));
dQ2_dL = 3*k2*mu**2*(G**2 - H**2)*(-e*(e*cos(f) + 2)*sin(f)*cos(f + 2*g) + (e**2 - 1)*sin(f + 2*g))/(4*G**3*L**3*e*(e**2 - 1));
dQ3_dL = k2*mu**2*(G**2 - H**2)*(-3*e*(e*cos(f) + 2)*sin(f)*cos(3*f + 2*g) + (e**2 - 1)*sin(3*f + 2*g))/(4*G**3*L**3*e*(e**2 - 1));
dP0_dG = k2*mu**2*(G**2*(G**2 - 3*H**2)*(e**2 - 1)*sin(f) - G**2*(G**2 - 3*H**2)*(e*cos(f) + 1)*(e*cos(f) + 2)*sin(f) + 3*L**2*e*(G**2 - 5*H**2)*(e**2 - 1)*(e*sin(f) + f - l_sym))/(2*G**6*L**2*e*(e**2 - 1));
dQ1_dG = 3*k2*mu**2*(2*G**2*(G**2 - H**2)*(e*cos(f) + 2)*sin(f)*cos(2*f + 2*g) + L**2*e*(-3*G**2 + 5*H**2)*(e**2 - 1)*sin(2*f + 2*g))/(4*G**6*L**2*e*(e**2 - 1));
dQ2_dG = 3*k2*mu**2*(G**2*e*(G**2 - H**2)*(e*cos(f) + 2)*sin(f)*cos(f + 2*g) - G**2*(G**2 - H**2)*(e**2 - 1)*sin(f + 2*g) + L**2*e**2*(-3*G**2 + 5*H**2)*(e**2 - 1)*sin(f + 2*g))/(4*G**6*L**2*e*(e**2 - 1));
dQ3_dG = k2*mu**2*(3*G**2*e*(G**2 - H**2)*(e*cos(f) + 2)*sin(f)*cos(3*f + 2*g) - G**2*(G**2 - H**2)*(e**2 - 1)*sin(3*f + 2*g) + L**2*e**2*(-3*G**2 + 5*H**2)*(e**2 - 1)*sin(3*f + 2*g))/(4*G**6*L**2*e*(e**2 - 1));
dP0_dH = 3*H*k2*mu**2*(e*sin(f) + f - l_sym)/G**5;
dQ1_dH = -3*H*k2*mu**2*sin(2*f + 2*g)/(2*G**5);
dQ2_dH = -3*H*e*k2*mu**2*sin(f + 2*g)/(2*G**5);
dQ3_dH = -H*e*k2*mu**2*sin(3*f + 2*g)/(2*G**5);
