#!/usr/bin/env python
"""IAU 2000A luni-solar nutation table transcription generator (R4b).

Reads the in-repo born-digital SOFA nut00a series
(sgp4_references/vallado_celestrak/datalib/iau00ansofa.dat: 678 luni-solar terms —
Delaunay multipliers L L' F D Om; longitude sin, t*sin, cos; obliquity cos, t*cos,
sin; all coefficients EXACT INTEGERS in 1e-7 arcsec) and EMITS the C++ rows for
src/astronomy/nutation_terms_iau2000a.h — the gen_lunar_terms.py pattern:
mechanical, reproducible, never typed from memory.

Also reads the planetary series (iau00anplsofa.dat, 687 terms) and emits its
TOTAL absolute amplitudes — the omitted-planetary accuracy floor the luni-solar-
only model deposits (we do not model the planetary terms; we bound them).

Rows are emitted SORTED by max(|psi_sin|, |eps_cos|) descending, so a truncated
n_terms evaluation keeps the largest terms and the runtime tail bound
Sum_{k>n} |A_k| is the honest truncation. Run: python tools/gen_nutation_terms.py
"""

LS = "sgp4_references/vallado_celestrak/datalib/iau00ansofa.dat"
PL = "sgp4_references/vallado_celestrak/datalib/iau00anplsofa.dat"

rows = []
with open(LS) as f:
    for ln in f:
        if ln.lstrip().startswith("#") or not ln.strip():
            continue
        p = ln.split()
        assert len(p) == 11, f"bad row: {ln}"
        mult = [int(x) for x in p[:5]]
        coef = [float(x) for x in p[5:]]
        for c in coef:
            assert c == int(c), f"non-integer coefficient: {ln}"
        rows.append((mult, [int(c) for c in coef]))

assert len(rows) == 678, f"expected 678 luni-solar terms, got {len(rows)}"
rows.sort(key=lambda r: max(abs(r[1][0]), abs(r[1][3])), reverse=True)

# Planetary totals (the omitted-model floor).
tot = [0, 0, 0, 0]   # |psi_sin|, |psi_cos|, |eps_sin|, |eps_cos|
n_pl = 0
with open(PL) as f:
    for ln in f:
        if ln.lstrip().startswith("#") or not ln.strip():
            continue
        p = ln.split()
        assert len(p) == 18, f"bad planetary row: {ln}"
        c = [float(x) for x in p[14:]]
        tot[0] += abs(c[0]); tot[1] += abs(c[1])
        tot[2] += abs(c[2]); tot[3] += abs(c[3])
        n_pl += 1

print("#pragma once")
print()
print("/// @file nutation_terms_iau2000a.h")
print("/// IAU 2000A LUNI-SOLAR nutation series -- AUTO-GENERATED by")
print("/// tools/gen_nutation_terms.py from the in-repo born-digital SOFA table")
print("/// (sgp4_references/vallado_celestrak/datalib/iau00ansofa.dat). Do not edit;")
print("/// re-run the generator. 678 terms, SORTED by amplitude so a truncated")
print("/// n_terms evaluation keeps the largest terms (the dial-up pattern).")
print("/// Coefficients are EXACT INTEGERS in 1e-7 arcsec (the SOFA unit):")
print("///   dpsi = sum (psi_sin + psi_t_sin*t) sin(th) + psi_cos cos(th)")
print("///   deps = sum (eps_cos + eps_t_cos*t) cos(th) + eps_sin sin(th)")
print("/// th = l*L + lp*L' + f*F + d*D + om*Om (the Delaunay arguments).")
print("/// The PLANETARY series (687 terms, iau00anplsofa.dat) is NOT modeled;")
print("/// its total |amplitude| is the omitted-model accuracy floor below.")
print("/// Theory: design/derivations/nutation_itrs.md.")
print()
print("namespace astronomy {")
print()
print("/// One luni-solar term: Delaunay multipliers + the six SOFA coefficients")
print("/// [1e-7 arcsec, exact integers].")
print("struct NutationTerm {")
print("    int l, lp, f, d, om;")
print("    long psi_sin, psi_t_sin, psi_cos;")
print("    long eps_cos, eps_t_cos, eps_sin;")
print("};")
print()
print(f"/// The {len(rows)} luni-solar terms, amplitude-sorted.")
print("inline constexpr NutationTerm kNutationIau2000a[] = {")
for (m, c) in rows:
    print(f"    {{{m[0]}, {m[1]}, {m[2]}, {m[3]}, {m[4]}, "
          f"{c[0]}, {c[1]}, {c[2]}, {c[3]}, {c[4]}, {c[5]}}},")
print("};")
print()
print("/// Number of luni-solar terms in kNutationIau2000a.")
print(f"inline constexpr int kNutationTermCount = {len(rows)};")
print()
print(f"/// Omitted PLANETARY-series dpsi floor: total |amplitude| over all {n_pl}")
print("/// planetary terms [1e-7 arcsec] (conservative triangle bound; measured by")
print("/// the generator from iau00anplsofa.dat).")
print(f"inline constexpr long kPlanetaryPsiFloor = {tot[0] + tot[1]:.0f};")
print("/// Omitted PLANETARY-series deps floor [1e-7 arcsec] (same basis).")
print(f"inline constexpr long kPlanetaryEpsFloor = {tot[2] + tot[3]:.0f};")
print()
print("} // namespace astronomy")
