#!/usr/bin/env python
"""Generate the born-digital Meeus §47 lunar periodic-term tables as a C++ header.

Source: pymeeus (architest/pymeeus), which realises Meeus, *Astronomical
Algorithms* Ch.47 (Tables 47.A longitude/distance, 47.B latitude) verbatim from
the ELP-2000/82 truncation. The amplitudes are EXACT INTEGERS in units of 1e-6
degree (longitude/latitude) and 1e-3 km (distance), so they carry no digit
truncation — the model's accuracy is purely the SERIES truncation (omitted terms)
plus the Meeus-60-vs-full-ELP floor, both tracked by the consumer.

The resulting model is verified against the INDEPENDENT astropy/ERFA oracle in
test_ephemeris (not against pymeeus) — pymeeus is only the born-digital SOURCE.
Run: `python tools/gen_lunar_terms.py`  →  src/ephemeris/lunar_terms_meeus.h
"""
import pymeeus.Moon as M

LR = M.PERIODIC_TERMS_LR_TABLE   # rows: [cD, cM, cM', cF, Σl(1e-6°), Σr(1e-3 km)]
B = M.PERIODIC_TERMS_B_TABLE     # rows: [cD, cM, cM', cF, Σb(1e-6°)]


def cell(x):
    xi = int(round(x))
    return str(xi) if float(xi) == float(x) else repr(x)


out = []
out.append("#pragma once\n")
out.append("""
/// @file lunar_terms_meeus.h
/// AUTO-GENERATED by tools/gen_lunar_terms.py — DO NOT EDIT BY HAND.
///
/// Born-digital Meeus §47 lunar periodic terms (Tables 47.A longitude/distance,
/// 47.B latitude), from pymeeus's verbatim realisation of the ELP-2000/82
/// truncation. Each row is the integer multipliers of the Delaunay arguments
/// (D, M, M', F) and the amplitude(s): Σl, Σb in 1e-6 degree, Σr in 1e-3 km. The
/// amplitudes are EXACT INTEGERS in those units (no digit truncation); the
/// model's accuracy is the SERIES truncation, tracked by the consumer
/// (ephemeris/moon_meeus.h). Rows are in Meeus's order (descending amplitude).
///
/// Verified (independent oracle): the assembled lunar position is gated against
/// astropy/ERFA (erfa.moon98) in test_ephemeris — NOT against pymeeus.
""")
out.append("namespace ephemeris {\n")
out.append("/// A longitude+distance term: amplitudes Σl [1e-6°], Σr [1e-3 km].\n")
out.append("struct LunarTermLR { int cD, cM, cMp, cF; double sig_l, sig_r; };\n")
out.append("/// A latitude term: amplitude Σb [1e-6°].\n")
out.append("struct LunarTermB { int cD, cM, cMp, cF; double sig_b; };\n\n")

out.append("/// Meeus Table 47.A: the longitude/distance periodic terms,\n")
out.append("/// Meeus order (arguments couple to the Sun via D and M).\n")
out.append(f"static const LunarTermLR kLunarLR[{len(LR)}] = {{\n")
for r in LR:
    out.append(f"    {{{int(r[0])}, {int(r[1])}, {int(r[2])}, {int(r[3])}, {cell(r[4])}, {cell(r[5])}}},\n")
out.append("};\n\n")

out.append("/// Meeus Table 47.B: the latitude periodic terms.\n")
out.append(f"static const LunarTermB kLunarB[{len(B)}] = {{\n")
for r in B:
    out.append(f"    {{{int(r[0])}, {int(r[1])}, {int(r[2])}, {int(r[3])}, {cell(r[4])}}},\n")
out.append("};\n\n")
out.append("} // namespace ephemeris\n")

with open("src/ephemeris/lunar_terms_meeus.h", "w", newline="\n", encoding="utf-8") as f:
    f.write("".join(out))
print(f"wrote src/ephemeris/lunar_terms_meeus.h: {len(LR)} LR + {len(B)} B terms")
